import { WorkoutDays } from "../workout-days";
import Link from "next/link";
import { and, asc, eq, inArray } from "drizzle-orm";
import { notFound } from "next/navigation";
import { db } from "@/db";
import { exercises, studentWorkouts, teacherStudents, users, workoutExercises, workoutGroups, workouts } from "@/db/schema";
import { signOut } from "@/app/auth-actions";
import { requireUser } from "@/lib/auth/session";
import { DashboardShell } from "@/app/dashboard/dashboard-shell";
import { LoadHistoryButton, LoadStepper } from "../load-controls";
import { AssignStudent } from "../assign-student";

export default async function WorkoutDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser();
  const { id } = await params;
  const [workout] = await db.select().from(workouts).where(and(eq(workouts.id, id), eq(workouts.createdBy, user.id))).limit(1);
  if (!workout) notFound();
  const backHref = workout.sheetId ? `/planilhas/${workout.sheetId}` : "/treinos";
  const backLabel = workout.sheetId ? "Voltar para planilha" : "Voltar para treinos";
  const groups = await db.select({ id: workoutGroups.id, type: workoutGroups.type, restSeconds: workoutGroups.restSeconds, orderIndex: workoutGroups.orderIndex }).from(workoutGroups).where(eq(workoutGroups.workoutId, workout.id)).orderBy(asc(workoutGroups.orderIndex));
  const items = groups.length ? await db.select({ id: workoutExercises.id, groupId: workoutExercises.groupId, name: exercises.name, sets: workoutExercises.sets, repetitions: workoutExercises.repetitions, load: workoutExercises.load, orderIndex: workoutExercises.orderIndex }).from(workoutExercises).innerJoin(exercises, eq(workoutExercises.exerciseId, exercises.id)).where(inArray(workoutExercises.groupId, groups.map((group) => group.id))).orderBy(asc(workoutExercises.orderIndex)) : [];
  const students = user.role === "professor" ? await db.select({ id: users.id, name: users.name, email: users.email }).from(teacherStudents).innerJoin(users, eq(users.id, teacherStudents.studentId)).where(and(eq(teacherStudents.teacherId, user.id), eq(users.role, "aluno"))).orderBy(users.name) : [];
  const assignments = user.role === "professor" ? await db.select({ studentId: studentWorkouts.studentId }).from(studentWorkouts).where(and(eq(studentWorkouts.teacherId, user.id), eq(studentWorkouts.sourceWorkoutId, workout.id))) : [];
  const actions = <div className="mt-5 flex flex-wrap gap-3"><Link href={`/treinos/${workout.id}/fazer`} prefetch={false} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">Treinar</Link>{user.role === "professor" ? <AssignStudent workoutId={workout.id} workoutName={workout.name} students={students} assignedIds={assignments.map((entry) => entry.studentId)} /> : null}</div>;
  return <DashboardShell user={user} signOut={signOut} activePage={workout.sheetId ? "sheets" : "workouts"}><div><Link href={backHref} className="text-sm text-slate-500 hover:text-slate-950">← {backLabel}</Link>{user.role !== "aluno" ? <Link href={`/treinos/${workout.id}/editar`} className="ml-4 inline-block rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">Editar treino</Link> : null}<div className="mb-8 mt-6"><span className="mb-3 block h-1 w-[30px] rounded-full bg-slate-950" /><p className="text-sm font-medium text-slate-400">Ficha de treino</p><div className="mt-3 flex items-center gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" className="size-5"><path strokeLinecap="round" strokeLinejoin="round" d="M6.5 6.5v11M3.5 9v6M17.5 6.5v11M20.5 9v6M6.5 12h11" /></svg></span><h1 className="min-w-0 text-2xl font-semibold tracking-tight sm:text-3xl">{workout.name}</h1></div><WorkoutDays days={workout.weekdays} />{workout.description ? <p className="mt-2 text-sm text-slate-500">{workout.description}</p> : null}{actions}</div><div className="space-y-5">{groups.map((group, index) => <section key={group.id} className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><h2 className="text-sm font-semibold text-slate-500">{`Série ${index + 1}`}</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead><tr className="border-b border-slate-100 text-xs font-medium uppercase tracking-wide text-slate-400"><th className="pb-3 pr-4">Exercício</th><th className="w-28 pb-3 text-center">Séries</th><th className="w-32 pb-3 text-center">Repetições</th><th className="w-28 pb-3 text-right">Carga</th></tr></thead><tbody className="divide-y divide-slate-100">{items.filter((item) => item.groupId === group.id).map((item) => <tr key={`${item.groupId}-${item.orderIndex}-${item.name}`}><td className="py-4 pr-4"><LoadHistoryButton workoutExerciseId={item.id} exerciseName={item.name} /></td><td className="py-4 text-center text-slate-500">{item.sets}</td><td className="py-4 text-center text-slate-500">{item.repetitions}</td><td className="py-4 text-right"><LoadStepper workoutExerciseId={item.id} initialLoad={item.load} /></td></tr>)}</tbody></table></div><p className="mt-3 text-sm text-slate-500">Intervalo entre séries: <strong className="text-slate-950">{group.restSeconds === null ? "--" : `${group.restSeconds}s`}</strong></p></section>)}</div></div></DashboardShell>;
}
